apiVersion: apps/v1
kind: Deployment
metadata:
  name: aceest-blue
  namespace: aceest
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aceest
      track: blue
  template:
    metadata:
      labels:
        app: aceest
        track: blue
    spec:
      containers:
      - name: aceest
        image: aceest:latest
        ports:
        - containerPort: 8000
